### ISSUE TITLE
Detect No Internet connection in tests and skip

### ISSUE THREAD

**Issue by layik** [ITSLeeds/stats19#14]
Struggling to find a good R code that can do this for some reason.

**Comment by layik** [comment]
https://stackoverflow.com/a/34970085/2332101

**Comment by mpadge** [comment]
I've got that all sorted from developing `osmdata` (and others) while constantly travelling in trains with really dodgy internet. Check it (or see, for example, [here](https://github.com/ropensci/osmdata/blob/master/tests/testthat/test-getbb.R))
```
has_internet <- curl::has_internet ()
if (has_internet){
    # do some internet-dependent tests
}
```
My larger flag of `test_all` also mocks `httr::GET` calls and so performs all tests without actually using `httr::GET` even when there is internet - this is really important on CRAN because a single internet failure will fail your package. There are easier ways to mock, via [`vcr` & co](https://github.com/ropensci/vcr), but those are not yet `httr`-compliant (they use [`crul`](https://github.com/ropensci/crul)).

**Comment by mpadge** [comment]
Let me know and I can easily develop mocking procedures for `stats19` - generally speaking, one should never make API calls on CRAN tests, and so mocking will be generally necessary.

**Comment by layik** [comment]
Thanks @mpadge! Just one example would be great please. Been trying to do a mock since `geoplumber` and not been able to.

**Comment by layik** [comment]
https://github.com/ropensci/osmdata/blob/8703f00ee458817961e2f69297772f24775a89d2/tests/testthat/test-osmdata.R#L10

**Comment by mpadge** [comment]
You `httr`-ing, or `crul`-ing? That determines everything ... And if `httr`-ing, could you envision converting? (See [these convincing arguments](https://masalmon.eu/2017/06/30/crolute/) from @maelle.)

**Comment by layik** [comment]
We use utils `download.file` not quite sure if it uses `libcurl` underneath. Its more of me not being able to write proper mocks than dealing with the request aspect of this to be honest. I could not find osmdata's mock functions maybe I should look closer.

**Comment by layik** [comment]
but now, for the connectivity check, we have dependency of `curl` package.

**Comment by layik** [comment]
Hi @mpadge, I am over the moon :) I do not think this comment by Jim can be found anywhere on the web 😛 
https://github.com/r-lib/testthat/issues/734#issuecomment-377367516

Now I can go
```
test_that("FINALLY!", {
  with_mock(
    "stats19:::dl_stats19" = function(x) x - 1,
    expect_equal(dl_stats19(2), 1)
  )
})```
now I can fake any 🚀

**Comment by mpadge** [comment]
But that won't fully test the code that processes the output of your `http` requests; it only mocks final end-points of functions. The idea behind `vcr` and my mocking code is that it mocks the underlying binary value returned from `httr::GET`, which itself directly calls `curl::GET` (ie, the `c` function). Mocking that is important to fully test every stage of processing requests.

And a further complication: one generally wants to test a variety of request results, yet simply mocking `httr::GET` in this way can only test a single kind of pre-specified result. Sorry to forecast just a wee shower upon your otherwise sparkling parade. I'll have a look through tomorrow and see what I can pull together as a PR.

**Comment by Robinlovelace** [comment]
Just picking up the thread on all this. I remember reading about mocks when `vcr` was first developed. I must admit I never fully understood it or got it working! Simple is good. I think [`skip_if_offline()`](https://github.com/r-lib/testthat/blob/e2703ca962af0419f122eb348b7a216e8861e887/R/skip.R#L107) may be the simplest solution. I suspect most tests will have an internet connection so it's OK if the full test online works online when you have the web: we'll find out sooner or later if the tests fail.

**Comment by mpadge** [comment]
Yeah, okay, the tests for this package are super simple, so no need to go overboard with complex mocking. I agree @Robinlovelace: All good.

**Comment by layik** [comment]
Well, sounds like we are [done](https://github.com/ITSLeeds/stats19/commit/c0e30261cecc5415e0b91c6ab74931055a31294b#diff-f07b233e7802daf7aa890475bbe4b97bR6) if this is acceptable to CRAN.

**Comment by mpadge** [comment]
It'll be acceptable to them - they don't actually check coverage directly, but they do these days quickly (automatically?) peruse the test directories. There are plenty of packages with no tests at all. The bigger issue will be that you'll have to be accepted by rOpenSci, and they have much higher standards for most things, including tests. But you'll get great feedback regardless, so it'll all be good and only get better.
