### ISSUE TITLE
Refactor file storage, names, and locate_ functions

### ISSUE THREAD

**Issue by mpadge** [ITSLeeds/stats19#25]
@layik I made a brief comment about the internal `stats19::file_list` being used to locate **downloaded** files. This currently happens in the [`read_`](https://github.com/ITSLeeds/stats19/blob/master/R/read_stats19.R) functions which call `check_input_file()`. This in turn directly calls `locate_one_file()` which calls `locate_files()` which calls `find_file_name()`, and the latter finally reads `stats19::file_list` and tries to match names of downloaded files to the list. The effect of all of this is that a list of the names of external `.zip` archives is being used to determine the names of files contained within them. This works in your current form because each `.zip` is extracted into its own folder of the same name, but it makes this whole file-checking procedure very convoluted and rather difficult to understand by an external person trying to peruse the code.

What I have implemented thus far, and that would be easy to follow through consistently in my current PR, is to:
1. Flat dump all files in the root of `data_dir`, and change names by
2. Appending years where these don't exist (like 2017)
3. Appending types where these don't exist, as "_acc", "_cas", or "_veh".

So, for example, 2017 accidents simply has "Acc.csv", so this is automatically converted to "Acc_2017.csv".

This procedure entirely avoids the current circuitous `read_...() -> check_input_file() -> locate_one_file() -> locate_files() -> find_file_name()`. Nearly all of these functions can simply be removed, and replaced with simple `grep`s of the file names for the appropriate year and type. Let me know what you think, and if you approve of the concept, I'll proceed with the refactor in the PR.

---

Edit: This will be particularly important for caching (#22), which will be equivalently enormously simpler in this form, compared with trying to cache a convoluted sub-directory structure in current form.

**Comment by layik** [comment]
Thanks @mpadge. Discussing these approaches is vital in my opinion and helps give the package a rationale and logical approach to a sound foundation.

As I said in the other threads, the rationale was to keep everything in sync with the source. Keeping those "zip" file names was the centre of it. I made my life difficult to achieve that. 

Otherwise, having got 52 file names with potentially x5 more files within each .zip file, we could easily even pre-load the package with the 52x5 names. This would add, clearly one abstraction over the `DfT`'s not so great naming conventions. So some documentation for the users would be "helpful", whilst  now, we would just say "You asked for x you got x".

So, the "circuitous" is really a "functional" way of managing above.

I am very happy to be in the back seat :)
